"""empty message

Revision ID: 43c78de1b605
Revises: 1c9bda0550ba
Create Date: 2015-10-23 08:40:47.723000

"""

# revision identifiers, used by Alembic.
revision = '43c78de1b605'
down_revision = '1c9bda0550ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
